//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbConection
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RolesPruebaEntities : DbContext
    {
        public RolesPruebaEntities()
            : base("name=RolesPruebaEntities")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            // Configuración de la eliminación en cascada de Cuestionarios a Preguntas
            modelBuilder.Entity<Cuestionarios>()
                .HasMany(c => c.Preguntas)
                .WithRequired(p => p.Cuestionarios)
                .HasForeignKey(p => p.IdCuestionario)
                .WillCascadeOnDelete(true);

            // Configuración de la eliminación en cascada de Preguntas a Respuestas
            modelBuilder.Entity<Preguntas>()
                .HasMany(p => p.Respuestas)
                .WithRequired(r => r.Preguntas)
                .HasForeignKey(r => r.IdPregunta)
                .WillCascadeOnDelete(true);

            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<Areas> Areas { get; set; }
        public virtual DbSet<Cuestionarios> Cuestionarios { get; set; }
        public virtual DbSet<Preguntas> Preguntas { get; set; }
        public virtual DbSet<Respuestas> Respuestas { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
    }
}
